package PLSQL;

/** ESTO ES UN PROCEDIMIENTO PARA INSERTAR_USUARIOS
 * 
 * @author JS
 */
public class INSERTA_USUARIO {

	public INSERTA_USUARIO() {
	}
	
	/*create or replace PROCEDURE INSERTA_USUARIO 
	(
	  P_NOMBRE IN VARCHAR2, 
	  P_DIRECCION IN VARCHAR2,
	  P_EMAIL IN VARCHAR2,
	  P_PASSWORD IN VARCHAR2
	)AS 
	  V_AUX NUMBER;
	BEGIN
	  DBMS_OUTPUT.PUT_LINE('PROCEDIMIENTO PARA INSERTAR UN NOMBRE EN LA BASE DATOS');
	  
	   COMPROBACION DE QUE NO HAYA UN USUARIO YA INTRODUCIDO CON EL MISMO NOMBRE EN LA BASE DATOS
	  SELECT COUNT(*)
	  INTO V_AUX
	  FROM USUARIOS
	  WHERE USUARIO=P_EMAIL;
	  
	  IF(V_AUX>0) THEN
	    INSERT INTO LOG VALUES(SYSDATE, 'SE HA INTENTADO REGISTRAR UN USUARIO YA EXISTENTE '||P_NOMBRE, 'registro');
	    COMMIT;
	    RAISE_APPLICATION_ERROR(-20001,'ESE USUARIO YA EXISTE EN LA BASE DE DATOS');
	  ELSE
	    INSERT INTO USUARIOS VALUES(P_NOMBRE,MD5HASH(P_PASSWORD));
	    INSERT INTO GRUPOS VALUES('sociosbiblioteca',P_NOMBRE); LUEGO TENGO Q BORRAR ESTA LINEA XQ SOLO QUIERO Q SE LOGUEE CON SU EMAIL
	    INSERT INTO GRUPOS VALUES('sociosbiblioteca',P_EMAIL);
	    INSERT INTO SOCIO VALUES(NEWUSERSECUENCIA.NEXTVAL,P_EMAIL,P_NOMBRE,P_DIRECCION);
	   END IF;
	  
	END INSERTA_USUARIO;*/

}
